--- mxml/Makefile.orig	2010-03-31 22:45:46.000000000 -0400
+++ mxml/Makefile	2010-03-31 22:47:03.000000000 -0400
@@ -88,7 +88,7 @@
 			mxml-node.o mxml-search.o mxml-set.o
 LIBOBJS		=	$(PUBLIBOBJS) mxml-private.o mxml-string.o
 OBJS		=	mxmldoc.o testmxml.o $(LIBOBJS)
-TARGETS		=	$(LIBMXML) mxmldoc testmxml mxml.xml doc/mxml.man
+TARGETS		=	$(LIBMXML)
 
 
 #
