--- mDNSResponder/mDNSPosix/Makefile.orig	2006-06-20 19:07:04.000000000 -0400
+++ mDNSResponder/mDNSPosix/Makefile	2010-05-29 17:25:43.000000000 -0400
@@ -316,6 +316,16 @@
 OPTINSTALL   = InstalledNSS
 else
 
+ifeq ($(os),uclinux)
+CC = $(CROSS_COMPILE)gcc $(CFLAGS)   
+LD = $(CROSS_COMPILE)gcc -shared $(CFLAGS) $(LDFLAGS)
+LINKOPTS = $(LDLIBS)
+CFLAGS_OS = -DNOT_HAVE_SA_LEN -DUSES_NETLINK -DHAVE_LINUX
+JAVACFLAGS_OS += -I$(JDK)/include/linux
+OPTIONALTARG = nss_mdns
+OPTINSTALL   = InstalledNSS
+else
+
 ifeq ($(os),netbsd)
 CFLAGS_OS =
 LDCONFIG = ldconfig
@@ -383,6 +393,7 @@
 endif
 endif
 endif
+endif
 
 NSSLIBNAME  := libnss_mdns
 NSSVERSION  := 0.2
