#Makefile for www directory
# (really just for install)

include ../makefile.inc

WWW_FILES= brwsniff.js favicon.ico index.html mpsutils.js uiutils.js Cookie.js backward.png forward.png navigatebackward.png navigateforward.png pause.png play.png  

.PHONY: install favicon.ico index.html mpsutils.js
install:
	cp $(WWW_FILES) $(MPSERVICE_WWW_DIR)
